# Terraform variable values for DaVinci export
# Generated by pingcli tf export

pingone_environment_id = "6b6bfb5d-8293-40d5-894e-0f74144334db"

# Pingone_davinci_connector_instance Variables

davinci_connection_Code_0020_Snippet_code                                                                       = "// Write your code here\n// Supported language: Javascript \nmodule.exports = async ({params}) => {\n\tconsole.log('params: ', params)\n\tconst parsed = JSON.parse(params.paramA)\n\tconst linkparsed = `[$${parsed.stringA},$${parsed.stringB}]`\n\tconst guid = 'xxxx-xxxx-xx-xxx-xx'.replace(/xy/g, function (c){\n\t\tconst r = Math.random() * 16 | 0,\n\t\t\tv = c === 'x' ? r : (r & 0x3 | 0x8);\n\t\treturn v.toString(16)\n\t})\n\treturn {\n\t\t'testVariable': params.testVariable, \n\t\t'linkparsed': linkparsed\n\t\t}\n}"
davinci_connection_Code_0020_Snippet_inputSchema                                                                = "{\n\t\"input\": {\n\t\t\"type\": \"object\",\n\t\t\"properties\": {\n\t\t\t\"testVariable\": {\n\t\t\t\t\"type\": \"string\"\n\t\t\t},\n\t\t\t\"paramA\": {\n\t\t\t\t\"type\": \"object\"\n\t\t\t}\n\t\t}\n\t}\n}"
davinci_connection_Code_0020_Snippet_outputSchema                                                               = "{\n\t\"output\": {\n\t\t\"type\": \"object\",\n\t\t\"properties\": {\n\t\t\t\"testVariable\": {\n\t\t\t\t\"type\": \"string\"\n\t\t\t},\n\t\t\t\"paramA\": {\n\t\t\t\t\"type\": \"object\"\n\t\t\t}\n\t\t}\n\t}\n}"
davinci_connection_IDmission_0020___0020_OIDC_0020___0020_test_0020_clone_0020_93b5_customAuth_authTypeDropdown = "openId"
davinci_connection_IDmission_0020___0020_OIDC_0020___0020_test_0020_clone_0020_93b5_customAuth_clientId         = "abcd"
davinci_connection_IDmission_0020___0020_OIDC_0020___0020_test_0020_clone_0020_93b5_customAuth_clientSecret     = "" # Secret value - provide manually
davinci_connection_IDmission_0020___0020_OIDC_0020___0020_test_0020_clone_0020_93b5_customAuth_providerName     = ""
davinci_connection_IDmission_0020___0020_OIDC_0020___0020_test_0020_clone_0020_93b5_customAuth_scope            = "openid"
davinci_connection_IDmission_0020___0020_OIDC_0020___0020_test_0020_clone_0020_93b5_customAuth_state            = "false"
davinci_connection_IDmission_0020___0020_OIDC_0020___0020_test_customAuth_authTypeDropdown                      = "openId"
davinci_connection_IDmission_0020___0020_OIDC_0020___0020_test_customAuth_clientId                              = "abcd"
davinci_connection_IDmission_0020___0020_OIDC_0020___0020_test_customAuth_clientSecret                          = "" # Secret value - provide manually
davinci_connection_IDmission_0020___0020_OIDC_0020___0020_test_customAuth_providerName                          = ""
davinci_connection_IDmission_0020___0020_OIDC_0020___0020_test_customAuth_scope                                 = "openid"
davinci_connection_IDmission_0020___0020_OIDC_0020___0020_test_customAuth_state                                 = "false"
davinci_connection_OIDC_0020__0026__0020_OAuth_0020_IdP_0020___0020_test_customAuth_clientSecret                = "" # Secret value - provide manually
davinci_connection_OIDC_0020__0026__0020_OAuth_0020_IdP_0020___0020_test_customAuth_customAttributes            = "[{\"attributeType\":\"sk\",\"description\":\"ID\",\"maxLength\":\"300\",\"minLength\":\"1\",\"name\":\"id\",\"required\":true,\"type\":\"string\",\"value\":null},{\"attributeType\":\"sk\",\"description\":\"Display Name\",\"maxLength\":\"250\",\"minLength\":\"1\",\"name\":\"name\",\"required\":false,\"type\":\"string\",\"value\":null},{\"attributeType\":\"sk\",\"description\":\"Email\",\"maxLength\":\"250\",\"minLength\":\"1\",\"name\":\"email\",\"required\":false,\"type\":\"string\",\"value\":null}]"
davinci_connection_OIDC_0020__0026__0020_OAuth_0020_IdP_0020___0020_test_customAuth_state                       = "false"
davinci_connection_OIDC_0020__0026__0020_OAuth_0020_IdP_0020__testB_customAuth_authorizationEndpoint            = "https://auth.pingone.com/authz"
davinci_connection_OIDC_0020__0026__0020_OAuth_0020_IdP_0020__testB_customAuth_authTypeDropdown                 = "openId"
davinci_connection_OIDC_0020__0026__0020_OAuth_0020_IdP_0020__testB_customAuth_clientId                         = "abcd"
davinci_connection_OIDC_0020__0026__0020_OAuth_0020_IdP_0020__testB_customAuth_clientSecret                     = "" # Secret value - provide manually
davinci_connection_OIDC_0020__0026__0020_OAuth_0020_IdP_0020__testB_customAuth_customAttributes                 = "[{\"attributeType\":\"sk\",\"description\":\"ID\",\"maxLength\":\"300\",\"minLength\":\"1\",\"name\":\"id\",\"required\":true,\"type\":\"string\",\"value\":null},{\"attributeType\":\"sk\",\"description\":\"Display Name\",\"maxLength\":\"250\",\"minLength\":\"1\",\"name\":\"name\",\"required\":false,\"type\":\"string\",\"value\":null},{\"attributeType\":\"sk\",\"description\":\"Email\",\"maxLength\":\"250\",\"minLength\":\"1\",\"name\":\"email\",\"required\":false,\"type\":\"string\",\"value\":null}]"
davinci_connection_OIDC_0020__0026__0020_OAuth_0020_IdP_0020__testB_customAuth_providerName                     = "pingone directory"
davinci_connection_OIDC_0020__0026__0020_OAuth_0020_IdP_0020__testB_customAuth_scope                            = "openid"
davinci_connection_OIDC_0020__0026__0020_OAuth_0020_IdP_0020__testB_customAuth_tokenEndpoint                    = "https://auth.pingone.com/authz"
davinci_connection_OIDC_0020__0026__0020_OAuth_0020_IdP_0020__testB_customAuth_userInfoEndpoint                 = "[\"https://auth.pingone.com/userInfo\"]"
davinci_connection_OIDC_0020__0026__0020_OAuth_0020_IdP_0020__testC_customAuth_authorizationEndpoint            = "https://auth.pingone.com/authz"
davinci_connection_OIDC_0020__0026__0020_OAuth_0020_IdP_0020__testC_customAuth_authTypeDropdown                 = "openId"
davinci_connection_OIDC_0020__0026__0020_OAuth_0020_IdP_0020__testC_customAuth_clientId                         = "abcd"
davinci_connection_OIDC_0020__0026__0020_OAuth_0020_IdP_0020__testC_customAuth_clientSecret                     = "" # Secret value - provide manually
davinci_connection_OIDC_0020__0026__0020_OAuth_0020_IdP_0020__testC_customAuth_customAttributes                 = "[{\"attributeType\":\"sk\",\"description\":\"ID\",\"maxLength\":\"300\",\"minLength\":\"1\",\"name\":\"id\",\"required\":true,\"type\":\"string\",\"value\":null},{\"attributeType\":\"sk\",\"description\":\"Display Name\",\"maxLength\":\"250\",\"minLength\":\"1\",\"name\":\"name\",\"required\":false,\"type\":\"string\",\"value\":null},{\"attributeType\":\"sk\",\"description\":\"Email\",\"maxLength\":\"250\",\"minLength\":\"1\",\"name\":\"email\",\"required\":false,\"type\":\"string\",\"value\":null}]"
davinci_connection_OIDC_0020__0026__0020_OAuth_0020_IdP_0020__testC_customAuth_providerName                     = "pingone directory"
davinci_connection_OIDC_0020__0026__0020_OAuth_0020_IdP_0020__testC_customAuth_scope                            = "openid"
davinci_connection_OIDC_0020__0026__0020_OAuth_0020_IdP_0020__testC_customAuth_tokenEndpoint                    = "https://auth.pingone.com/authz"
davinci_connection_OIDC_0020__0026__0020_OAuth_0020_IdP_0020__testC_customAuth_userInfoEndpoint                 = "[\"https://auth.pingone.com/userInfo\"]"
davinci_connection_OIDC_0020__0026__0020_OAuth_0020_IdP_0020__testD_customAuth_authorizationEndpoint            = "https://auth.pingone.com/authz"
davinci_connection_OIDC_0020__0026__0020_OAuth_0020_IdP_0020__testD_customAuth_authTypeDropdown                 = "openId"
davinci_connection_OIDC_0020__0026__0020_OAuth_0020_IdP_0020__testD_customAuth_clientId                         = "abcd"
davinci_connection_OIDC_0020__0026__0020_OAuth_0020_IdP_0020__testD_customAuth_clientSecret                     = "" # Secret value - provide manually
davinci_connection_OIDC_0020__0026__0020_OAuth_0020_IdP_0020__testD_customAuth_customAttributes                 = "[{\"attributeType\":\"sk\",\"description\":\"ID\",\"maxLength\":\"300\",\"minLength\":\"1\",\"name\":\"id\",\"required\":true,\"type\":\"string\",\"value\":null},{\"attributeType\":\"sk\",\"description\":\"Display Name\",\"maxLength\":\"250\",\"minLength\":\"1\",\"name\":\"name\",\"required\":false,\"type\":\"string\",\"value\":null},{\"attributeType\":\"sk\",\"description\":\"Email\",\"maxLength\":\"250\",\"minLength\":\"1\",\"name\":\"email\",\"required\":false,\"type\":\"string\",\"value\":null}]"
davinci_connection_OIDC_0020__0026__0020_OAuth_0020_IdP_0020__testD_customAuth_providerName                     = "pingone directory"
davinci_connection_OIDC_0020__0026__0020_OAuth_0020_IdP_0020__testD_customAuth_scope                            = "openid"
davinci_connection_OIDC_0020__0026__0020_OAuth_0020_IdP_0020__testD_customAuth_tokenEndpoint                    = "https://auth.pingone.com/authz"
davinci_connection_OIDC_0020__0026__0020_OAuth_0020_IdP_0020__testD_customAuth_userInfoEndpoint                 = "[\"https://auth.pingone.com/userInfo\"]"
davinci_connection_PingOne_0020_MFA_clientId                                                                    = "7bd3c212-19ca-404e-a303-63cb95afe4de"
davinci_connection_PingOne_0020_MFA_clientSecret                                                                = "" # Secret value - provide manually
davinci_connection_PingOne_0020_MFA_envId                                                                       = "6b6bfb5d-8293-40d5-894e-0f74144334db"
davinci_connection_PingOne_0020_MFA_policyId                                                                    = "f4278391-7170-0572-170c-d8addf9b7a6f"
davinci_connection_PingOne_0020_MFA_region                                                                      = "NA"
davinci_connection_PingOne_0020_Notifications_clientId                                                          = "7bd3c212-19ca-404e-a303-63cb95afe4de"
davinci_connection_PingOne_0020_Notifications_clientSecret                                                      = "" # Secret value - provide manually
davinci_connection_PingOne_0020_Notifications_envId                                                             = "6b6bfb5d-8293-40d5-894e-0f74144334db"
davinci_connection_PingOne_0020_Notifications_region                                                            = "NA"
davinci_connection_PingOne_0020_Protect_clientId                                                                = "7bd3c212-19ca-404e-a303-63cb95afe4de"
davinci_connection_PingOne_0020_Protect_clientSecret                                                            = "" # Secret value - provide manually
davinci_connection_PingOne_0020_Protect_envId                                                                   = "6b6bfb5d-8293-40d5-894e-0f74144334db"
davinci_connection_PingOne_0020_Protect_region                                                                  = "NA"
davinci_connection_PingOne_clientId                                                                             = "7bd3c212-19ca-404e-a303-63cb95afe4de"
davinci_connection_PingOne_clientSecret                                                                         = "" # Secret value - provide manually
davinci_connection_PingOne_envId                                                                                = "6b6bfb5d-8293-40d5-894e-0f74144334db"
davinci_connection_PingOne_region                                                                               = "NA"

# Pingone_davinci_form Variables

davinci_form_example___sign_on = "6a31188b-f784-44c9-950f-b8194ae37a33"

# Pingone_davinci_variable Variables

davinci_variable_buttonValue_value                 = "Accept"
davinci_variable_ciam_accountRecoveryEnabled_value = "true"
davinci_variable_ciam_agreementEnabled_value       = "true"
davinci_variable_ciam_appleEnabled_value           = "true"
davinci_variable_ciam_companyName_value            = "Ping Identity"
davinci_variable_ciam_emailOtpEnabled_value        = "true"
davinci_variable_ciam_facebookEnabled_value        = "true"
davinci_variable_ciam_fidoPasskeyEnabled_value     = "false"
davinci_variable_ciam_googleEnabled_value          = "true"
davinci_variable_ciam_logoStyle_value              = "width: 65px; height: 65px;"
davinci_variable_ciam_logoUrl_value                = "https://assets.pingone.com/ux/ui-library/5.0.2/images/logo-pingidentity.png"
davinci_variable_ciam_magicLinkEnabled_value       = "true"
davinci_variable_ciam_mobilePushOtpEnabled_value   = "true"
davinci_variable_ciam_otpFallbackAllowed_value     = "true"
davinci_variable_ciam_passwordlessRequired_value   = "false"
davinci_variable_ciam_recoveryLimit_value          = "5"
davinci_variable_ciam_requireMFA_value             = "true"
davinci_variable_ciam_resendOtpLimit_value         = "5"
davinci_variable_ciam_sessionLengthInMinute_value  = "5"
davinci_variable_ciam_smsOtpEnabled_value          = "true"
davinci_variable_ciam_totpEnabled_value            = "true"
davinci_variable_ciam_verificationLimit_value      = "5"
davinci_variable_ciam_voiceOtpEnabled_value        = "true"
davinci_variable_companyContextVar_value           = "foobar"
davinci_variable_flowRequireMFA_value              = "false"
davinci_variable_hideSkipButton_value              = "false"
davinci_variable_name_value                        = "value"
davinci_variable_registrationAgreementId_value     = "2dac0183-b5db-441a-88cd-a4651b32935f"
davinci_variable_registrationPopulationId_value    = "4d1fffc6-9404-4eaf-81db-52b741e36746"
davinci_variable_testPW_value                      = "" # Secret value - provide manually

